version: "3"

services:

  vsftpd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: always
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
      - ./cert:/etc/vsftpd/cert
    environment:
      - FTP_USER=test
      - FTP_PASS=test
      - SSL_ENABLE=NO
      - TLS_CERT=my_certificate.crt
      - TLS_KEY=my_key.key
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
